'use client'
// will recieve a repos prop
import React from 'react'
const Work = () => {


    let repos = [
        {
            "id": 502267298,
            "node_id": "R_kgDOHe_9og",
            "name": "A-three-production",
            "full_name": "faaiz99/A-three-production",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/A-three-production",
            "description": "to run the project use CMD and go to project's directory and run command php artisan serve. ",
            "fork": false,
            "url": "https://api.github.com/repos/faaiz99/A-three-production",
            "forks_url": "https://api.github.com/repos/faaiz99/A-three-production/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/A-three-production/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/A-three-production/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/A-three-production/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/A-three-production/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/A-three-production/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/A-three-production/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/A-three-production/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/A-three-production/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/A-three-production/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/A-three-production/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/A-three-production/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/A-three-production/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/A-three-production/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/A-three-production/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/A-three-production/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/A-three-production/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/A-three-production/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/A-three-production/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/A-three-production/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/A-three-production/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/A-three-production/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/A-three-production/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/A-three-production/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/A-three-production/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/A-three-production/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/A-three-production/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/A-three-production/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/A-three-production/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/A-three-production/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/A-three-production/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/A-three-production/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/A-three-production/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/A-three-production/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/A-three-production/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/A-three-production/deployments",
            "created_at": "2022-06-11T06:16:19Z",
            "updated_at": "2023-07-14T08:07:08Z",
            "pushed_at": "2022-07-24T10:57:04Z",
            "git_url": "git://github.com/faaiz99/A-three-production.git",
            "ssh_url": "git@github.com:faaiz99/A-three-production.git",
            "clone_url": "https://github.com/faaiz99/A-three-production.git",
            "svn_url": "https://github.com/faaiz99/A-three-production",
            "homepage": null,
            "size": 61412,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "PHP",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "main"
        },
        {
            "id": 598721008,
            "node_id": "R_kgDOI6_B8A",
            "name": "animavita",
            "full_name": "faaiz99/animavita",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/animavita",
            "description": "Trigger life-saving alerts, register animals for adoption and find the closest pet friend to adopt :dog:",
            "fork": true,
            "url": "https://api.github.com/repos/faaiz99/animavita",
            "forks_url": "https://api.github.com/repos/faaiz99/animavita/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/animavita/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/animavita/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/animavita/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/animavita/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/animavita/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/animavita/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/animavita/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/animavita/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/animavita/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/animavita/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/animavita/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/animavita/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/animavita/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/animavita/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/animavita/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/animavita/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/animavita/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/animavita/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/animavita/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/animavita/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/animavita/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/animavita/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/animavita/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/animavita/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/animavita/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/animavita/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/animavita/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/animavita/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/animavita/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/animavita/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/animavita/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/animavita/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/animavita/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/animavita/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/animavita/deployments",
            "created_at": "2023-02-07T17:20:04Z",
            "updated_at": "2023-02-07T15:47:57Z",
            "pushed_at": "2023-02-07T17:21:11Z",
            "git_url": "git://github.com/faaiz99/animavita.git",
            "ssh_url": "git@github.com:faaiz99/animavita.git",
            "clone_url": "https://github.com/faaiz99/animavita.git",
            "svn_url": "https://github.com/faaiz99/animavita",
            "homepage": "",
            "size": 7345,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": null,
            "has_issues": false,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": {
                "key": "gpl-2.0",
                "name": "GNU General Public License v2.0",
                "spdx_id": "GPL-2.0",
                "url": "https://api.github.com/licenses/gpl-2.0",
                "node_id": "MDc6TGljZW5zZTg="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "v2"
        },
        {
            "id": 627072441,
            "node_id": "R_kgDOJWBduQ",
            "name": "DevOps-2",
            "full_name": "faaiz99/DevOps-2",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/DevOps-2",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/faaiz99/DevOps-2",
            "forks_url": "https://api.github.com/repos/faaiz99/DevOps-2/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/DevOps-2/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/DevOps-2/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/DevOps-2/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/DevOps-2/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/DevOps-2/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/DevOps-2/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/DevOps-2/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/DevOps-2/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/DevOps-2/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/DevOps-2/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/DevOps-2/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/DevOps-2/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/DevOps-2/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/DevOps-2/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/DevOps-2/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/DevOps-2/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/DevOps-2/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/DevOps-2/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/DevOps-2/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/DevOps-2/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/DevOps-2/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/DevOps-2/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/DevOps-2/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/DevOps-2/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/DevOps-2/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/DevOps-2/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/DevOps-2/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/DevOps-2/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/DevOps-2/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/DevOps-2/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/DevOps-2/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/DevOps-2/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/DevOps-2/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/DevOps-2/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/DevOps-2/deployments",
            "created_at": "2023-04-12T18:17:08Z",
            "updated_at": "2023-04-12T18:17:16Z",
            "pushed_at": "2023-05-27T10:09:08Z",
            "git_url": "git://github.com/faaiz99/DevOps-2.git",
            "ssh_url": "git@github.com:faaiz99/DevOps-2.git",
            "clone_url": "https://github.com/faaiz99/DevOps-2.git",
            "svn_url": "https://github.com/faaiz99/DevOps-2",
            "homepage": null,
            "size": 6812,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "master"
        },
        {
            "id": 651627726,
            "node_id": "R_kgDOJtcMzg",
            "name": "devOps-3-Test-Cases",
            "full_name": "faaiz99/devOps-3-Test-Cases",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/devOps-3-Test-Cases",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases",
            "forks_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/devOps-3-Test-Cases/deployments",
            "created_at": "2023-06-09T17:06:24Z",
            "updated_at": "2023-06-09T17:06:31Z",
            "pushed_at": "2023-06-09T17:57:26Z",
            "git_url": "git://github.com/faaiz99/devOps-3-Test-Cases.git",
            "ssh_url": "git@github.com:faaiz99/devOps-3-Test-Cases.git",
            "clone_url": "https://github.com/faaiz99/devOps-3-Test-Cases.git",
            "svn_url": "https://github.com/faaiz99/devOps-3-Test-Cases",
            "homepage": null,
            "size": 11,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "main"
        },

        {
            "id": 583045421,
            "node_id": "R_kgDOIsCRLQ",
            "name": "LMS",
            "full_name": "faaiz99/LMS",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/LMS",
            "description": "This repository is dedicated to the semester project of TCS also known as LMS.",
            "fork": true,
            "url": "https://api.github.com/repos/faaiz99/LMS",
            "forks_url": "https://api.github.com/repos/faaiz99/LMS/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/LMS/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/LMS/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/LMS/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/LMS/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/LMS/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/LMS/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/LMS/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/LMS/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/LMS/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/LMS/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/LMS/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/LMS/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/LMS/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/LMS/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/LMS/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/LMS/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/LMS/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/LMS/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/LMS/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/LMS/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/LMS/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/LMS/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/LMS/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/LMS/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/LMS/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/LMS/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/LMS/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/LMS/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/LMS/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/LMS/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/LMS/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/LMS/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/LMS/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/LMS/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/LMS/deployments",
            "created_at": "2022-12-28T15:47:50Z",
            "updated_at": "2022-12-29T12:51:05Z",
            "pushed_at": "2023-01-01T09:42:06Z",
            "git_url": "git://github.com/faaiz99/LMS.git",
            "ssh_url": "git@github.com:faaiz99/LMS.git",
            "clone_url": "https://github.com/faaiz99/LMS.git",
            "svn_url": "https://github.com/faaiz99/LMS",
            "homepage": null,
            "size": 5035,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "JavaScript",
            "has_issues": false,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "master"
        },
        {
            "id": 620276047,
            "node_id": "R_kgDOJPipTw",
            "name": "mind-care-backend",
            "full_name": "faaiz99/mind-care-backend",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/mind-care-backend",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/faaiz99/mind-care-backend",
            "forks_url": "https://api.github.com/repos/faaiz99/mind-care-backend/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/mind-care-backend/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/mind-care-backend/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/mind-care-backend/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/mind-care-backend/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/mind-care-backend/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/mind-care-backend/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/mind-care-backend/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/mind-care-backend/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/mind-care-backend/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/mind-care-backend/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/mind-care-backend/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/mind-care-backend/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/mind-care-backend/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/mind-care-backend/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/mind-care-backend/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/mind-care-backend/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/mind-care-backend/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/mind-care-backend/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/mind-care-backend/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/mind-care-backend/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/mind-care-backend/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/mind-care-backend/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/mind-care-backend/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/mind-care-backend/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/mind-care-backend/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/mind-care-backend/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/mind-care-backend/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/mind-care-backend/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/mind-care-backend/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/mind-care-backend/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/mind-care-backend/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/mind-care-backend/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/mind-care-backend/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/mind-care-backend/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/mind-care-backend/deployments",
            "created_at": "2023-03-28T11:21:15Z",
            "updated_at": "2023-07-22T14:50:53Z",
            "pushed_at": "2023-08-01T21:18:02Z",
            "git_url": "git://github.com/faaiz99/mind-care-backend.git",
            "ssh_url": "git@github.com:faaiz99/mind-care-backend.git",
            "clone_url": "https://github.com/faaiz99/mind-care-backend.git",
            "svn_url": "https://github.com/faaiz99/mind-care-backend",
            "homepage": "",
            "size": 4639,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "master"
        },
        {
            "id": 620272095,
            "node_id": "R_kgDOJPiZ3w",
            "name": "mind-care-front-end",
            "full_name": "faaiz99/mind-care-front-end",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/mind-care-front-end",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/faaiz99/mind-care-front-end",
            "forks_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/mind-care-front-end/deployments",
            "created_at": "2023-03-28T11:11:09Z",
            "updated_at": "2023-05-21T06:42:28Z",
            "pushed_at": "2023-05-21T13:22:10Z",
            "git_url": "git://github.com/faaiz99/mind-care-front-end.git",
            "ssh_url": "git@github.com:faaiz99/mind-care-front-end.git",
            "clone_url": "https://github.com/faaiz99/mind-care-front-end.git",
            "svn_url": "https://github.com/faaiz99/mind-care-front-end",
            "homepage": null,
            "size": 10880,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 1,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 1,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "master"
        },
        {
            "id": 619837959,
            "node_id": "R_kgDOJPH6Bw",
            "name": "mind-care-mobile",
            "full_name": "faaiz99/mind-care-mobile",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/mind-care-mobile",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/faaiz99/mind-care-mobile",
            "forks_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/mind-care-mobile/deployments",
            "created_at": "2023-03-27T14:18:36Z",
            "updated_at": "2023-03-27T14:19:53Z",
            "pushed_at": "2023-03-27T14:19:10Z",
            "git_url": "git://github.com/faaiz99/mind-care-mobile.git",
            "ssh_url": "git@github.com:faaiz99/mind-care-mobile.git",
            "clone_url": "https://github.com/faaiz99/mind-care-mobile.git",
            "svn_url": "https://github.com/faaiz99/mind-care-mobile",
            "homepage": null,
            "size": 186,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "master"
        },
        {
            "id": 579468786,
            "node_id": "R_kgDOIon98g",
            "name": "Music-Player",
            "full_name": "faaiz99/Music-Player",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/Music-Player",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/faaiz99/Music-Player",
            "forks_url": "https://api.github.com/repos/faaiz99/Music-Player/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/Music-Player/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/Music-Player/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/Music-Player/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/Music-Player/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/Music-Player/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/Music-Player/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/Music-Player/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/Music-Player/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/Music-Player/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/Music-Player/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/Music-Player/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/Music-Player/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/Music-Player/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/Music-Player/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/Music-Player/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/Music-Player/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/Music-Player/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/Music-Player/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/Music-Player/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/Music-Player/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/Music-Player/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/Music-Player/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/Music-Player/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/Music-Player/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/Music-Player/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/Music-Player/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/Music-Player/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/Music-Player/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/Music-Player/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/Music-Player/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/Music-Player/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/Music-Player/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/Music-Player/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/Music-Player/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/Music-Player/deployments",
            "created_at": "2022-12-17T19:52:51Z",
            "updated_at": "2023-03-07T17:32:02Z",
            "pushed_at": "2023-03-15T15:18:50Z",
            "git_url": "git://github.com/faaiz99/Music-Player.git",
            "ssh_url": "git@github.com:faaiz99/Music-Player.git",
            "clone_url": "https://github.com/faaiz99/Music-Player.git",
            "svn_url": "https://github.com/faaiz99/Music-Player",
            "homepage": null,
            "size": 4248,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 2,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 1,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 2,
            "open_issues": 1,
            "watchers": 0,
            "default_branch": "main"
        },
        {
            "id": 641036690,
            "node_id": "R_kgDOJjVxkg",
            "name": "next-portfolio",
            "full_name": "faaiz99/next-portfolio",
            "private": false,
            "owner": {
                "login": "faaiz99",
                "id": 44613754,
                "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
                "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/faaiz99",
                "html_url": "https://github.com/faaiz99",
                "followers_url": "https://api.github.com/users/faaiz99/followers",
                "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
                "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
                "organizations_url": "https://api.github.com/users/faaiz99/orgs",
                "repos_url": "https://api.github.com/users/faaiz99/repos",
                "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
                "received_events_url": "https://api.github.com/users/faaiz99/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/faaiz99/next-portfolio",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/faaiz99/next-portfolio",
            "forks_url": "https://api.github.com/repos/faaiz99/next-portfolio/forks",
            "keys_url": "https://api.github.com/repos/faaiz99/next-portfolio/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/faaiz99/next-portfolio/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/faaiz99/next-portfolio/teams",
            "hooks_url": "https://api.github.com/repos/faaiz99/next-portfolio/hooks",
            "issue_events_url": "https://api.github.com/repos/faaiz99/next-portfolio/issues/events{/number}",
            "events_url": "https://api.github.com/repos/faaiz99/next-portfolio/events",
            "assignees_url": "https://api.github.com/repos/faaiz99/next-portfolio/assignees{/user}",
            "branches_url": "https://api.github.com/repos/faaiz99/next-portfolio/branches{/branch}",
            "tags_url": "https://api.github.com/repos/faaiz99/next-portfolio/tags",
            "blobs_url": "https://api.github.com/repos/faaiz99/next-portfolio/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/faaiz99/next-portfolio/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/faaiz99/next-portfolio/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/faaiz99/next-portfolio/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/faaiz99/next-portfolio/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/faaiz99/next-portfolio/languages",
            "stargazers_url": "https://api.github.com/repos/faaiz99/next-portfolio/stargazers",
            "contributors_url": "https://api.github.com/repos/faaiz99/next-portfolio/contributors",
            "subscribers_url": "https://api.github.com/repos/faaiz99/next-portfolio/subscribers",
            "subscription_url": "https://api.github.com/repos/faaiz99/next-portfolio/subscription",
            "commits_url": "https://api.github.com/repos/faaiz99/next-portfolio/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/faaiz99/next-portfolio/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/faaiz99/next-portfolio/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/faaiz99/next-portfolio/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/faaiz99/next-portfolio/contents/{+path}",
            "compare_url": "https://api.github.com/repos/faaiz99/next-portfolio/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/faaiz99/next-portfolio/merges",
            "archive_url": "https://api.github.com/repos/faaiz99/next-portfolio/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/faaiz99/next-portfolio/downloads",
            "issues_url": "https://api.github.com/repos/faaiz99/next-portfolio/issues{/number}",
            "pulls_url": "https://api.github.com/repos/faaiz99/next-portfolio/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/faaiz99/next-portfolio/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/faaiz99/next-portfolio/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/faaiz99/next-portfolio/labels{/name}",
            "releases_url": "https://api.github.com/repos/faaiz99/next-portfolio/releases{/id}",
            "deployments_url": "https://api.github.com/repos/faaiz99/next-portfolio/deployments",
            "created_at": "2023-05-15T16:36:09Z",
            "updated_at": "2023-05-15T16:43:39Z",
            "pushed_at": "2023-08-07T18:39:39Z",
            "git_url": "git://github.com/faaiz99/next-portfolio.git",
            "ssh_url": "git@github.com:faaiz99/next-portfolio.git",
            "clone_url": "https://github.com/faaiz99/next-portfolio.git",
            "svn_url": "https://github.com/faaiz99/next-portfolio",
            "homepage": "https://faaiz-portfolio.vercel.app",
            "size": 122,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [

            ],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "main"
        },
    ]

    let user = {
        "login": "faaiz99",
        "id": 44613754,
        "node_id": "MDQ6VXNlcjQ0NjEzNzU0",
        "avatar_url": "https://avatars.githubusercontent.com/u/44613754?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/faaiz99",
        "html_url": "https://github.com/faaiz99",
        "followers_url": "https://api.github.com/users/faaiz99/followers",
        "following_url": "https://api.github.com/users/faaiz99/following{/other_user}",
        "gists_url": "https://api.github.com/users/faaiz99/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/faaiz99/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/faaiz99/subscriptions",
        "organizations_url": "https://api.github.com/users/faaiz99/orgs",
        "repos_url": "https://api.github.com/users/faaiz99/repos",
        "events_url": "https://api.github.com/users/faaiz99/events{/privacy}",
        "received_events_url": "https://api.github.com/users/faaiz99/received_events",
        "type": "User",
        "site_admin": false,
        "name": null,
        "company": null,
        "blog": "",
        "location": null,
        "email": null,
        "hireable": true,
        "bio": null,
        "twitter_username": null,
        "public_repos": 18,
        "public_gists": 0,
        "followers": 5,
        "following": 6,
        "created_at": "2018-10-30T15:15:56Z",
        "updated_at": "2023-08-08T05:47:03Z"
    }



    return (
        <>
            <p className="mt-12 mb-12 text-4xl text-center font-semibold  text-zinc-200 sm:text-4xl md:text-5xl lg:text-6xl xl:text-6xl" id="work">My
                <span className="text-4xl sm:text-4xl md:text-5xl lg:text-6xl xl:text-6xl text-green-500 font-extrabold">      Coding </span>
                Crafts</p>
            <div className="flex flex-wrap justify-center  md:flex md:flex-row lg:flex lg:flex-row xl:flex xl:flex-row  gap-4 p-2">
                <div className=" hover:shadow-lg hover:shadow-zinc-500 flex flex-col gap-6 bg-zinc-900 p-8  rounded-3xl h-48 w-48">
                    <p className="text-xl text-center font-semibold  text-zinc-400">Total Repos</p>

                    <p className="text-zinc-200 text-center text-4xl font-extrabold">

                        {repos.length}
                    </p>

                </div>
                <div className=" hover:shadow-lg hover:shadow-zinc-500 flex flex-col gap-6 bg-zinc-900 p-8  rounded-3xl h-48 w-48">
                    <p className="text-xl text-center font-semibold  text-zinc-400">Followers</p>

                    <p className="text-zinc-200 text-center text-4xl font-extrabold">
                        {user.followers}
                    </p>
                </div>
                <div className=" hover:shadow-lg hover:shadow-zinc-500 flex flex-col gap-6 bg-zinc-900 p-8  rounded-3xl h-48 w-96">
                    <p className="text-xl text-center font-semibold  text-zinc-400">Last Updated</p>

                    <p className="text-zinc-200 text-center text-4xl font-extrabold">
                        {user.updated_at.slice(0, 10)}
                    </p>
                </div>
                <div className=" hover:shadow-lg hover:shadow-zinc-500 flex flex-col gap-6 bg-zinc-900 p-8  rounded-3xl h-48 w-96">
                    <p className="text-xl text-center font-semibold  text-zinc-400">Account Created</p>

                    <p className="text-zinc-200 text-center text-4xl font-extrabold">
                        {user.created_at.slice(0, 10)}
                    </p>
                </div>
            </div>
            <div className="overflow-x-auto mt-12 mb-12 px-12  lg:flex lg:justify-center" >
                <table className=" text-sm text-left text-gray-400 rounded-lg sm:w-5/6 md:w-5/6 lg:w-5/6 xl:w-5/6" >
                    <thead className="text-xs uppercase bg-zinc-800 text-gray-400">
                        <tr>
                            <th scope="col" className="px-6 py-3">
                                Project
                            </th>
                            <th scope="col" className="px-6 py-3">
                                <div className="flex items-center">
                                    Description
                                </div>
                            </th>
                            <th scope="col" className="px-6 py-3">
                                <div className="flex items-center">
                                    Open Issues
                                </div>
                            </th>
                            <th scope="col" className="px-6 py-3">
                                <div className="flex items-center">
                                    Forks

                                </div>
                            </th>
                            <th scope="col" className="px-9 py-3">
                                <div className="flex items-center">
                                    Created At

                                </div>
                            </th>
                            <th scope="col" className="px-9 py-3">
                                <div className="flex items-center">
                                    Updated At
                                </div>
                            </th>
                            <th scope="col" className="px-6 py-3">
                                <div className="flex items-center">
                                    Github Link
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {repos.map(repo => {
                            return (<React.Fragment key = {repo.id}>
                                <tr className=" border-b bg-zinc-700 ">
                                    <th scope="row" className="px-6 py-4 font-medium  whitespace-nowrap text-white"  >
                                        {repo.name}
                                    </th>
                                    <td className="px-6 py-4"  >
                                        {repo.description}
                                    </td>
                                    <td className="px-6 py-4">
                                        {repo.open_issues_count}
                                    </td>
                                    <td className="px-6 py-4" >
                                        {repo.forks_count}
                                    </td>
                                    <td className="px-6 py-4" >
                                        {repo.created_at.slice(0, 10)}
                                    </td>
                                    <td className="px-6 py-4" >
                                        {repo.updated_at.slice(0, 10)}
                                    </td>
                                    <td className="px-6 py-4">
                                        <a href={repo.html_url} target="_blank" className="font-medium text-blue-600  hover:font-bold hover:text-blue-400">Link</a>
                                    </td>
                                </tr>
                                </React.Fragment>)

                        })}
                    </tbody>
                </table>
            </div>

        </>

    );
}

export default Work;