name: Build and Deploy
on:
  workflow_call:
  push:
    branches: ["development", "main"]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["main"]

jobs:
  Lint-Format:
    uses: "./.github/workflows/eslint.yml"

  Test:
    uses: "./.github/workflows/test.yml"

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Conditional deployment for development (preview) branches
      - name: Deploy to Preview
        if: github.ref == 'refs/heads/development'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: '' # You c if needed
          working-directory: .
      
      # Conditional deployment for the main branch (production)
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: '--prod' # Deploy to production
          working-directory: .